# Generated by Django 5.1.2 on 2024-10-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usermodel_groups_usermodel_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
